### ISSUE TITLE
Error if load GitHub raw file

### ISSUE THREAD

**Issue by cvpe** [mikaelho/pythonista-webview#1]
I just started to use your (marvelous) script because I want to reach the raw page of a github file and the UIWebView does not provide the url of this page as it does not contain any html and webview.evaluate_javascript('window.location.href')  returns an empty string (it is normal).
Your script provides this url in will_start_loading but crashes with:
Traceback (most recent call last):
  File "/var/mobile/Containers/Shared/AppGroup/668A7D98-7216-47ED-917D-AA0B6173167E/Pythonista3/Documents/site-packages/wkwebview/wkwebview.py", line 578, in webview_did_finish_load
    print('Finished loading ' + webview.eval_js('document.title'))
TypeError: must be str, not NoneType

Not vital, just to warn you
Thanks for usual marvelous work

**Comment by mikaelho** [comment]
Thanks, I added str() there. Wondering if `eval_js` should always wrap the return value in a string, but not doing it for now.
